# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html flake8
    
    - name: Create reports directory
      run: mkdir -p reports
    
    - name: Run tests with pytest
      run: |
        pytest --html=reports/report.html --self-contained-html --pep8
    
    - name: Upload test report
      uses: actions/upload-artifact@v4  # Updated to v4
      if: always()
      with:
        name: pytest-report
        path: reports/report.html
    
    - name: Lint with flake8
      run: |
        flake8 src tests --count --show-source --statistics
